// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClCRKBKphgQ9xI9ZH7enH3cyyVTp0GKXE',
    appId: '1:82551381303:web:b8c785b4465d408d7f4eb2',
    messagingSenderId: '82551381303',
    projectId: 'pet-health-app-18255',
    authDomain: 'pet-health-app-18255.firebaseapp.com',
    storageBucket: 'pet-health-app-18255.firebasestorage.app',
    measurementId: 'G-S7BT7KEJGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg4R9VUJjbR13VMHaPD1pL6vW-SyeFc8I',
    appId: '1:82551381303:android:9dadfd4fe9f03ad97f4eb2',
    messagingSenderId: '82551381303',
    projectId: 'pet-health-app-18255',
    storageBucket: 'pet-health-app-18255.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLTOtwQZF-JWIYqX3x4udFQQzCj5qpxW4',
    appId: '1:82551381303:ios:7283dde68adb96d87f4eb2',
    messagingSenderId: '82551381303',
    projectId: 'pet-health-app-18255',
    storageBucket: 'pet-health-app-18255.firebasestorage.app',
    iosBundleId: 'com.example.petHealth',
  );
}
